source :rubygems

gem 'sinatra'
gem 'ripple'
gem 'riak-sessions'
gem 'omniauth'

# OAuth provider
gem 'rack-oauth2-server', :git => 'git://github.com/dreverri/rack-oauth2-server.git', :branch => 'ripple'

group :development do
  gem 'rake'
  gem 'rack-test'
  gem 'rspec'
end
